# Generated by Django 3.2.11 on 2022-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaas', '0002_quizinvitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinvitations',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
